import React, { useState, useEffect, useMemo } from "react";
import { apiFetch } from "../services/apiClient";
import { generateInvoiceHTML } from "./Sales/SalesInvoices";
import { useApiInvoices } from "../hooks/useApiInvoices";

export default function InvoicesPage({ userEmail }) {
  const [selectedInvoice, setSelectedInvoice] = useState(null);
  const [downloadNotice, setDownloadNotice] = useState(null);

  const { invoices: apiInvoices, refreshInvoices } = useApiInvoices();

  const invoices = useMemo(() => {
    return apiInvoices.map((inv) => {
      const docType = String(inv.type || inv.documentType || inv.invoiceType || "");
      const isProforma = docType.toLowerCase().includes("proforma") || docType.toLowerCase().includes("performa") || docType.toLowerCase().includes("pro forma");
      if (!isProforma || (inv.status || "").toLowerCase() === "paid") {
        return { ...inv, status: "Paid" };
      }
      if (!inv.status) {
        return { ...inv, status: "Pending" };
      }
      return inv;
    });
  }, [apiInvoices]);

  function triggerDownload(inv) {
    const htmlContent = generateInvoiceHTML(inv);

    const printWindow = window.open("", "_blank");
    if (printWindow) {
      printWindow.document.write(htmlContent);
      printWindow.document.close();
      printWindow.focus();
      setTimeout(() => {
        printWindow.print();
      }, 400);
    }

    const blob = new Blob([htmlContent], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${inv.id}_Agnivridhi_${(inv.type || "Invoice").replace(/\s+/g, "_")}.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    setDownloadNotice(`Downloaded official invoice file for ${inv.id}!`);
  }

  async function handlePayNow(inv) {
    try {
      const res = await apiFetch(`/invoices/${inv.id}/payments`, {
        method: "POST",
        body: JSON.stringify({
          amount: Number(inv.amount || 0),
          paymentMode: "ONLINE",
          remarks: "Client portal payment",
        })
      });

      if (res.ok) {
        refreshInvoices();
        setDownloadNotice(`Payment for ${inv.id} completed successfully! Status updated to Paid.`);
      } else {
        const err = await res.json();
        console.error(err);
        setDownloadNotice(`Payment simulation active. API returned: ${err.message || 'Error'}`);
      }
    } catch (e) {
      console.warn("Could not update invoice payment status:", e);
      setDownloadNotice(`Payment simulated.`);
    }

    setSelectedInvoice(null);
  }

  return (
    <div className="cd-subpage-container">
      {/* Header Intro */}
      <div className="cd-subpage-intro">
        <div>
          <span className="cd-kicker">BILLING & INVOICES</span>
          <h2>Client Invoices</h2>
          <p>Download official Tax & Proforma invoices issued for your account and pay outstanding balances online.</p>
        </div>
        <span className="cd-count-pill">{invoices.length} Invoice{invoices.length !== 1 ? "s" : ""} On Record</span>
      </div>

      {/* Download Alert Notice */}
      {downloadNotice && (
        <div className="cd-alert-success-banner">
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
          <span>{downloadNotice}</span>
          <button type="button" onClick={() => setDownloadNotice(null)}>×</button>
        </div>
      )}

      {/* Invoices Table Card */}
      <div className="cd-section-card" style={{ padding: 0, overflow: 'hidden' }}>
        <div className="cd-section-head" style={{ padding: '24px 28px 16px', margin: 0 }}>
          <div>
            <span className="cd-kicker">BILLING RECORD</span>
            <h2 style={{ fontSize: 20 }}>Client Invoices</h2>
          </div>
        </div>

        <div className="cd-table-wrap">
          {invoices.length === 0 ? (
            <div style={{ padding: "40px 20px", textAlign: "center", color: "#666" }}>
              <p style={{ fontSize: 16, fontWeight: 600, margin: "0 0 6px 0" }}>No Invoices Issued Yet</p>
              <p style={{ fontSize: 13, margin: 0 }}>Invoices generated by your sales representative will appear here automatically.</p>
            </div>
          ) : (
            <table className="cd-invoices-table">
              <thead>
                <tr>
                  <th>Invoice ID</th>
                  <th>Document Type</th>
                  <th>Client Name</th>
                  <th>Service Description</th>
                  <th>Issue Date</th>
                  <th>Status</th>
                  <th style={{ textAlign: "right" }}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {invoices.map((inv) => {
                  const docType = String(inv.type || inv.documentType || inv.invoiceType || "");
                  const isProforma = docType.toLowerCase().includes("proforma") || docType.toLowerCase().includes("performa") || docType.toLowerCase().includes("pro forma");
                  const isPaid = !isProforma || (inv.status || "").toLowerCase() === "paid";
                  const showPayNow = !isPaid && isProforma;
                  const rate = Number(inv.rate || inv.pitchedAmount || inv.amount || 0);
                  const gst = Number(inv.gstPercent) !== undefined ? Number(inv.gstPercent) : 18;
                  const total = inv.totalAmount ? Number(inv.totalAmount) : (rate * (1 + gst / 100));
                  const formattedTotal = `₹${Math.round(total).toLocaleString("en-IN")}`;

                  return (
                    <tr key={inv.id}>
                      <td>
                        <strong className="cd-inv-id">{inv.id}</strong>
                      </td>
                      <td>
                        <span style={{ fontSize: 12, fontWeight: 600, color: isProforma ? "#f59e0b" : "#1877f2" }}>
                          {inv.type || inv.documentType || "Tax Invoice"}
                        </span>
                      </td>
                      <td>{inv.clientName || "Client"}</td>
                      <td>{inv.description || "Business Consultancy Services"}</td>
                      <td>{inv.issueDate || "Today"}</td>
                      <td>
                        <span
                          className={`cd-doc-status-badge ${isPaid ? "verified" : "pending"}`}
                          style={{
                            background: isPaid ? "rgba(68, 191, 176, 0.12)" : "rgba(245, 158, 11, 0.12)",
                            color: isPaid ? "#2b9e90" : "#d97706",
                            borderColor: isPaid ? "rgba(68, 191, 176, 0.3)" : "rgba(245, 158, 11, 0.3)"
                          }}
                        >
                          {isPaid ? "Paid" : "Not Paid"}
                        </span>
                      </td>
                      <td>
                        <div style={{ display: 'flex', gap: 8, justifyContent: 'flex-end' }}>
                          <button
                            type="button"
                            className="cd-table-action-btn"
                            style={{ background: 'rgba(68, 191, 176, 0.1)', color: '#44bfb0', borderColor: 'rgba(68, 191, 176, 0.3)' }}
                            onClick={() => triggerDownload(inv)}
                            title="Download Invoice File"
                          >
                            <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" style={{ marginRight: 4 }}><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
                            Download PDF
                          </button>
                          <button
                            type="button"
                            className="cd-table-action-btn"
                            style={showPayNow ? { background: '#1877f2', color: '#fff', borderColor: '#1877f2', fontWeight: 600 } : {}}
                            onClick={() => setSelectedInvoice({ ...inv, isPaid, formattedTotal, isProforma })}
                          >
                            {showPayNow ? "Pay Now" : "Inspect"}
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          )}
        </div>
      </div>

      {/* Invoice Inspection & Download Modal */}
      {selectedInvoice && (
        <div className="cd-modal-backdrop" onMouseDown={() => setSelectedInvoice(null)}>
          <section className="cd-modal cd-modal-sm" onMouseDown={(e) => e.stopPropagation()}>
            <button type="button" className="cd-modal-close" onClick={() => setSelectedInvoice(null)}>×</button>
            <span
              className={`cd-doc-status-badge ${selectedInvoice.isPaid ? "verified" : "pending"}`}
              style={{
                marginBottom: 12,
                background: selectedInvoice.isPaid ? "rgba(68, 191, 176, 0.12)" : "rgba(245, 158, 11, 0.12)",
                color: selectedInvoice.isPaid ? "#2b9e90" : "#d97706"
              }}
            >
              {selectedInvoice.isPaid ? "Paid & Cleared" : "Not Paid (Pending)"}
            </span>
            <h2>{selectedInvoice.id} ({selectedInvoice.type || "Invoice"})</h2>
            <p className="cd-modal-desc">{selectedInvoice.description || "Business Consultancy Services"}</p>

            <div className="cd-scheme-meta-box" style={{ gridTemplateColumns: '1fr 1fr', marginBottom: 20 }}>
              <div>
                <span>Billed To</span>
                <strong>{selectedInvoice.clientName || "Client"}</strong>
              </div>
              <div>
                <span>GSTIN</span>
                <strong>{selectedInvoice.gstin || "N/A"}</strong>
              </div>
              <div>
                <span>Base Rate</span>
                <strong>₹{Number(selectedInvoice.rate || 0).toLocaleString("en-IN")}</strong>
              </div>
              <div>
                <span>GST ({selectedInvoice.gstPercent || 18}%)</span>
                <strong>₹{Number(selectedInvoice.totalGst || 0).toLocaleString("en-IN")}</strong>
              </div>
              <div>
                <span>Total Amount Due</span>
                <strong style={{ color: '#4e7cff' }}>{selectedInvoice.formattedTotal}</strong>
              </div>
              <div>
                <span>Place of Supply</span>
                <strong>{selectedInvoice.placeOfSupply || "Uttar Pradesh"}</strong>
              </div>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              <button
                type="button"
                className="cd-submit-btn"
                style={{ background: 'linear-gradient(135deg, #1877f2 0%, #0056b3 100%)' }}
                onClick={() => triggerDownload(selectedInvoice)}
              >
                Print / Download Official PDF Invoice ({selectedInvoice.id})
              </button>

              {!selectedInvoice.isPaid && selectedInvoice.isProforma && (
                <button
                  type="button"
                  className="cd-submit-btn"
                  onClick={() => handlePayNow(selectedInvoice)}
                >
                  Pay {selectedInvoice.formattedTotal} Online
                </button>
              )}
            </div>
          </section>
        </div>
      )}
    </div>
  );
}
