import { normalizeSalesPersonName } from "./branchHelper";

export function parseRevenueValue(rev) {
  if (typeof rev === "number") return rev;
  if (!rev) return 0;
  const str = String(rev).replace(/[^0-9.]/g, "");
  const val = parseFloat(str);
  return isNaN(val) ? 0 : val;
}

/**
 * Net payment formula: Math.round(Gross Payment / 1.18)
 * Excludes 18% GST (payment / 1.18)
 */
export function parseNetRevenue(val) {
  const gross = parseRevenueValue(val);
  if (gross <= 0) return 0;
  return Math.round(gross / 1.18);
}

export function parseDate(value) {
  if (!value) return new Date();
  if (value instanceof Date) return value;
  if (typeof value === "number") return new Date(value);
  const str = String(value).trim();
  if (!str) return new Date();

  // YYYY-MM-DD
  if (/^\d{4}-\d{2}-\d{2}$/.test(str)) {
    const [y, m, d] = str.split("-").map(Number);
    return new Date(y, m - 1, d);
  }

  const parsed = new Date(str);
  return isNaN(parsed.getTime()) ? new Date() : parsed;
}

export function isSameDay(dateA, dateB) {
  if (!dateA || !dateB) return false;
  return (
    dateA.getFullYear() === dateB.getFullYear() &&
    dateA.getMonth() === dateB.getMonth() &&
    dateA.getDate() === dateB.getDate()
  );
}

export function isSameWeek(date, referenceDate) {
  if (!date || !referenceDate) return false;
  const startOfWeek = new Date(referenceDate);
  const day = startOfWeek.getDay();
  // Monday as first day of week (1 for Mon, 0 for Sun -> -6)
  const diff = startOfWeek.getDate() - day + (day === 0 ? -6 : 1);
  startOfWeek.setDate(diff);
  startOfWeek.setHours(0, 0, 0, 0);

  const endOfWeek = new Date(startOfWeek);
  endOfWeek.setDate(startOfWeek.getDate() + 6);
  endOfWeek.setHours(23, 59, 59, 999);

  return date >= startOfWeek && date <= endOfWeek;
}

export function isSameMonth(date, referenceDate) {
  if (!date || !referenceDate) return false;
  return (
    date.getFullYear() === referenceDate.getFullYear() &&
    date.getMonth() === referenceDate.getMonth()
  );
}

export function formatCurrency(value) {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(value || 0);
}

/**
 * Calculates dynamic Daily, Weekly, and Monthly payment totals
 * connected directly to the revenue generated by each salesperson of the sales team.
 * Net payment formula: Math.round(Gross Payment / 1.18)
 */
export function calculatePaymentMetricsFromClients(clients = [], branchTeam = [], selectedSalesPerson = "all") {
  const today = new Date();

  // Lookup map for branch sales team members
  const salesMap = new Map();

  const getSalesObj = (rawName, defaultRole = "Sales Representative", defaultBranch = "Branch") => {
    const normName = normalizeSalesPersonName(rawName) || "Unassigned";
    if (!salesMap.has(normName)) {
      salesMap.set(normName, {
        id: normName,
        name: normName,
        role: defaultRole,
        branch: defaultBranch,
        quota: "₹100k",
        daily: 0,
        weekly: 0,
        monthly: 0,
        total: 0,
        latestTimestamp: null,
        dealCount: 0,
        deals: [],
      });
    }
    return salesMap.get(normName);
  };

  // Seed sales team members from branchTeam prop
  if (Array.isArray(branchTeam)) {
    branchTeam.forEach((member) => {
      if (!member) return;
      const mName = typeof member === "string" ? member : (member.name || member.fullName || "");
      if (mName) {
        getSalesObj(mName, member.role || "Sales Representative", member.branch || "Branch");
      }
    });
  }

  // Set of team names for fast filtering if selected filter is active
  const selectedNorm = selectedSalesPerson && selectedSalesPerson !== "all" ? normalizeSalesPersonName(selectedSalesPerson).toLowerCase() : null;

  // Track processed payment keys to avoid double counting
  const processedPaymentKeys = new Set();

  const addPaymentEntry = (grossAmount, dateInput, rawRepName, clientName = "", paymentId = "") => {
    const gross = parseRevenueValue(grossAmount);
    if (gross <= 0) return;

    const netAmt = parseNetRevenue(gross);
    const pDate = parseDate(dateInput);
    const repName = normalizeSalesPersonName(rawRepName) || "Unassigned";

    if (selectedNorm && repName.toLowerCase() !== selectedNorm) {
      return;
    }

    const payKey = paymentId ? `${paymentId}` : `${repName.toLowerCase()}::${clientName.toLowerCase()}::${gross}::${pDate.toISOString().slice(0, 10)}`;
    if (processedPaymentKeys.has(payKey)) return;
    processedPaymentKeys.add(payKey);

    const spData = getSalesObj(repName);

    const isToday = isSameDay(pDate, today);
    const isThisWeek = isSameWeek(pDate, today);
    const isThisMonth = isSameMonth(pDate, today);

    spData.total += netAmt;
    spData.monthly += netAmt;
    spData.dealCount += 1;
    spData.deals.push({ company: clientName, amount: netAmt, grossAmount: gross, date: pDate });

    if (isToday) {
      spData.daily += netAmt;
      spData.weekly += netAmt;
    } else if (isThisWeek) {
      spData.weekly += netAmt;
    }

    if (!spData.latestTimestamp || pDate > spData.latestTimestamp) {
      spData.latestTimestamp = pDate;
    }
  };



  // 2. Scan clients list (paymentsHistory & paymentReceived)
  if (Array.isArray(clients)) {
    clients.forEach((c) => {
      if (!c) return;
      const repName = c.salesRep || c.assignedSalesPerson || c.salesPerson || c.owner || "Sales Executive";
      const companyName = c.company || c.companyName || c.name || "Client Entity";

      // Check for detailed payment transactions in payments, paymentsHistory, or invoices.payments
      const subPayments = Array.isArray(c.payments) && c.payments.length > 0
        ? c.payments
        : (Array.isArray(c.paymentsHistory) && c.paymentsHistory.length > 0
          ? c.paymentsHistory
          : (Array.isArray(c.invoices) && c.invoices.some(inv => Array.isArray(inv.payments) && inv.payments.length > 0)
            ? c.invoices.flatMap(inv => inv.payments || [])
            : null));

      if (subPayments && subPayments.length > 0) {
        subPayments.forEach((p) => {
          if (!p) return;
          const st = (p.status || "").toLowerCase();
          if (st !== "failed" && st !== "cancelled") {
            const amt = p.amount || p.paidAmount || 0;
            const dt = p.paymentDate || p.date || p.createdAt || c.updatedAt || c.startDate;
            const pRep = p.salesPerson || p.salesRep || repName;
            addPaymentEntry(amt, dt, pRep, companyName, p.id || p.paymentId ? `cl-pay-${p.id || p.paymentId}` : "");
          }
        });
      } else {
        // Fallback to paymentReceived or totalPayment if completed
        const rec = parseRevenueValue(c.paymentReceived || (c.paymentStatus === "Paid" ? c.totalPayment || c.amount : 0));
        if (rec > 0) {
          const dt = c.updatedAt || c.lastPaymentDate || c.paymentDate || c.createdAt || c.startDate || c.assignedAt;
          addPaymentEntry(rec, dt, repName, companyName, c.id ? `cl-rec-${c.id}` : "");
        }
      }
    });
  }

  const breakdownArray = Array.from(salesMap.values());

  let grandDaily = 0;
  let grandWeekly = 0;
  let grandMonthly = 0;
  let grandTotal = 0;

  breakdownArray.forEach((sp) => {
    grandDaily += sp.daily;
    grandWeekly += sp.weekly;
    grandMonthly += sp.monthly;
    grandTotal += sp.total;
  });

  // Ensure logical scaling: daily <= weekly <= monthly
  if (grandWeekly < grandDaily) grandWeekly = grandDaily;
  if (grandMonthly < grandWeekly) grandMonthly = grandWeekly;

  return {
    dailyTotal: grandDaily,
    weeklyTotal: grandWeekly,
    monthlyTotal: grandMonthly,
    grandTotal,
    breakdown: breakdownArray,
  };
}

export function getDailyPayment(managerId) {
  return 20000;
}

export function getWeeklyPayment(managerId) {
  return 79000;
}

export function getMonthlyPayment(managerId) {
  return 181000;
}

