import {
  getTrackerStages,
  getTrackerState,
  normalizeCompletedStages,
  getProcessTypeForScheme,
  getCanonicalSchemeName,
  TRACKER_STAGES_DEFINITIONS,
  SCHEME_PROCESS_TYPE_MAP,
} from "../../utils/schemeTracker";

export {
  getTrackerStages,
  getTrackerState,
  normalizeCompletedStages,
  getProcessTypeForScheme,
  getCanonicalSchemeName,
  TRACKER_STAGES_DEFINITIONS,
  SCHEME_PROCESS_TYPE_MAP,
};

export const initialBranches = [
  {
    id: "BR-01",
    name: "West Zone (Mumbai)",
    city: "Mumbai, Maharashtra",
    branchManager: "Ariana Lee",
    salesManager: "Eli Brooks",
    manager: "Ariana Lee",
    adminLead: "Vikramaditya Roy",
    headcount: 10,
    employeeCount: 9,
    salesManagerCount: 1,
    activeClients: 0,
    target: "₹4,500,000",
    achieved: "₹0",
    status: "Active",
  },
  {
    id: "BR-02",
    name: "North Zone (Delhi)",
    city: "New Delhi, NCR",
    branchManager: "Rajesh Khanna",
    salesManager: "Ananya Sen",
    manager: "Rajesh Khanna",
    adminLead: "Amit Joshi",
    headcount: 10,
    employeeCount: 9,
    salesManagerCount: 1,
    activeClients: 0,
    target: "₹3,800,000",
    achieved: "₹0",
    status: "Active",
  },
  {
    id: "BR-03",
    name: "South Zone (Bengaluru)",
    city: "Bengaluru, Karnataka",
    branchManager: "Suresh Reddy",
    salesManager: "Karthik Iyer",
    manager: "Suresh Reddy",
    adminLead: "Lakshmi Narayanan",
    headcount: 10,
    employeeCount: 9,
    salesManagerCount: 1,
    activeClients: 0,
    target: "₹4,200,000",
    achieved: "₹0",
    status: "Active",
  },
  {
    id: "BR-04",
    name: "East Zone (Kolkata)",
    city: "Kolkata, West Bengal",
    branchManager: "Subhash Banerjee",
    salesManager: "Debolina Roy",
    manager: "Subhash Banerjee",
    adminLead: "Pronab Paul",
    headcount: 10,
    employeeCount: 9,
    salesManagerCount: 1,
    activeClients: 0,
    target: "₹2,500,000",
    achieved: "₹0",
    status: "Active",
  },
];

// Default generic 5-stage list (CRM Creation -> Agreement -> Reports -> Application -> Final)
export const ACTIVITY_STAGES = getTrackerStages("PMEGP");

export const APPLICATION_STAGES = ACTIVITY_STAGES;

export const initialBranchClients = [];

export const initialBranchTeam = [
  // West Zone (Mumbai)
  {
    id: 1,
    name: "Ariana Lee",
    role: "Branch Manager",
    branch: "West Zone (Mumbai)",
    email: "ariana@agni.com",
    phone: "+91 98202 22334",
    assignedClients: 18,
    status: "Active",
  },
  {
    id: 2,
    name: "Eli Brooks",
    role: "Sales Manager",
    branch: "West Zone (Mumbai)",
    email: "eli@agni.com",
    phone: "+91 98201 11223",
    assignedClients: 25,
    status: "Active",
  },
  {
    id: 3,
    name: "Mia Rose",
    role: "Sales Person",
    branch: "West Zone (Mumbai)",
    email: "mia@agni.com",
    phone: "+91 98205 55667",
    assignedClients: 14,
    status: "Active",
  },
  {
    id: 4,
    name: "Lucas Scott",
    role: "Sales Person",
    branch: "West Zone (Mumbai)",
    email: "lucas@agni.com",
    phone: "+91 98205 55670",
    assignedClients: 10,
    status: "Active",
  },
  // North Zone (Delhi)
  {
    id: 5,
    name: "Rajesh Khanna",
    role: "Branch Manager",
    branch: "North Zone (Delhi)",
    email: "rajesh.bm@agni.com",
    phone: "+91 98111 11223",
    assignedClients: 12,
    status: "Active",
  },
  {
    id: 6,
    name: "Ananya Sen",
    role: "Sales Manager",
    branch: "North Zone (Delhi)",
    email: "ananya.sm@agni.com",
    phone: "+91 98111 22334",
    assignedClients: 20,
    status: "Active",
  },
  {
    id: 7,
    name: "Rohan Gupta",
    role: "Sales Person",
    branch: "North Zone (Delhi)",
    email: "rohan.sales@agni.com",
    phone: "+91 98111 44556",
    assignedClients: 12,
    status: "Active",
  },
  {
    id: 8,
    name: "Kavya Sharma",
    role: "Sales Person",
    branch: "North Zone (Delhi)",
    email: "kavya.sales@agni.com",
    phone: "+91 98111 66778",
    assignedClients: 9,
    status: "Active",
  },
  // South Zone (Bengaluru)
  {
    id: 9,
    name: "Suresh Reddy",
    role: "Branch Manager",
    branch: "South Zone (Bengaluru)",
    email: "suresh.bm@agni.com",
    phone: "+91 98450 11122",
    assignedClients: 15,
    status: "Active",
  },
  {
    id: 10,
    name: "Karthik Iyer",
    role: "Sales Manager",
    branch: "South Zone (Bengaluru)",
    email: "karthik.sm@agni.com",
    phone: "+91 98450 22233",
    assignedClients: 22,
    status: "Active",
  },
  {
    id: 11,
    name: "Arjun Hegde",
    role: "Sales Person",
    branch: "South Zone (Bengaluru)",
    email: "arjun.sales@agni.com",
    phone: "+91 98450 33445",
    assignedClients: 11,
    status: "Active",
  },
  {
    id: 12,
    name: "Deepa Rao",
    role: "Sales Person",
    branch: "South Zone (Bengaluru)",
    email: "deepa.sales@agni.com",
    phone: "+91 98450 44556",
    assignedClients: 8,
    status: "Active",
  },
  // East Zone (Kolkata)
  {
    id: 13,
    name: "Subhash Banerjee",
    role: "Branch Manager",
    branch: "East Zone (Kolkata)",
    email: "subhash.bm@agni.com",
    phone: "+91 98330 11223",
    assignedClients: 10,
    status: "Active",
  },
  {
    id: 14,
    name: "Debolina Roy",
    role: "Sales Manager",
    branch: "East Zone (Kolkata)",
    email: "debolina.sm@agni.com",
    phone: "+91 98330 44557",
    assignedClients: 18,
    status: "Active",
  },
  {
    id: 15,
    name: "Sourav Das",
    role: "Sales Person",
    branch: "East Zone (Kolkata)",
    email: "sourav.sales@agni.com",
    phone: "+91 98330 44558",
    assignedClients: 0,
    status: "Active",
  },
  {
    id: 16,
    name: "Riya Mukherjee",
    role: "Sales Person",
    branch: "East Zone (Kolkata)",
    email: "riya.sales@agni.com",
    phone: "+91 98330 44559",
    assignedClients: 2,
    status: "Active",
  },
];

export const stageBadgeColors = {
  "CRM Creation": "#10b981",
  "Agreement": "#4e7cff",
  "Reports": "#9a74e9",
  "Application": "#f2aa38",
  "Interview": "#ec4899",
  "Final": "#10b981",
  "Submission": "#10b981",
  "Doc Audit": "#9a74e9",
  "Manager Review": "#f2aa38",
  "Final Approval": "#10b981",
  "Active & Disbursed": "#10b981",
  "Document Verification": "#9a74e9",
  Underwriting: "#f2aa38",
  Approved: "#26a69a",
  Submitted: "#4e7cff",
  "On Hold": "#ff9800",
  Rejected: "#ff5757",
};

export const formatCurrency = (val) =>
  new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(val || 0);
